name: rollback

on:
  workflow_dispatch:

concurrency: prr:deploy

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        ref: 'next'
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx pr-release rollback --verbose --target main --source next --verbose --ignore 'package*' --ignore changelog.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}